version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test

  # build-and-test:
  #   docker:
  #     - image: cimg/node:20.0.0
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - node/with-cache:
  #         steps:
  #           - run: npm install
  #           - run: npm test
  #           - run: npm run build
workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build