version: 2.1
 
jobs:
  build:
    docker:
      - image: cimg/node:20.0.0
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test